### ISSUE TITLE
Deployed to Vercel with 404 Not Found result

### ISSUE THREAD

**Issue by arbisyarifudin** [imbhargav5/nextbase-nextjs-supabase-starter#33]
Hi, i use your template, and do some page and functionality.
But when it deployed to Vercel, it's always turns 404.

You can check this.
https://fsc-sd-web2-3k2x8jpz9-arbis-projects-2fa9c352.vercel.app

**Comment by arbisyarifudin** [comment]
Hi. I run the build again and but the result is:
![image](https://github.com/user-attachments/assets/5fab0f07-5b5c-4073-823a-df2142659a51)
https://fsc-sd-web2-git-main-test-arbis-projects-2fa9c352.vercel.app/?_vercel_share=AnHcaMF8drBKWMPKsTwqUI4uAPwHpIpQ

and the logs is:
```
TypeError: Cannot read properties of undefined (reading 'getSession')
    at m (/var/task/.next/server/app/(dynamic-pages)/(main-pages)/page.js:1:6628)
    at y (/var/task/.next/server/app/(dynamic-pages)/(main-pages)/page.js:1:6860)
    at eh (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
    at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475) {
  digest: '2243357109'
}
```

**Comment by arbisyarifudin** [comment]
the problem is i think from this file: `(dynamic-pages)/layout.tsx`

```
import { DynamicLayoutProviders } from './DynamicLayoutProviders';
import { AppSupabaseClient } from '@/types';
import { createSupabaseServerComponentClient } from '@/supabase-clients/createSupabaseServerComponentClient';

// do not cache this layout
export const dynamic = 'force-dynamic';
export const fetchCache = 'only-no-store';
export const revalidate = 0;

async function fetchSession(supabaseClient: AppSupabaseClient) {
  // This is a server-side call, so it will not trigger a revalidation
  const {
    data: { session },
    error,
  } = await supabaseClient.auth.getSession();

  if (error) {
    throw error;
  }

  return session;
}

export const metadata = {
  icons: {
    icon: '/images/logo-black-main.ico',
  },
  title: 'Super Day',
  description: 'Super Day',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabaseClient = createSupabaseServerComponentClient();
  const [session] = await Promise.all([fetchSession(supabaseClient)]);
  return (
    <DynamicLayoutProviders initialSession={session}>
      {children}
    </DynamicLayoutProviders>
  );
}

```

**Comment by vednig** [comment]
Hey @arbisyarifudin, did you solve the issue I am getting the same problem recently, I have tried lot of things but none seem to be working.

**Comment by vednig** [comment]
@imbhargav5 a little help here?

**Comment by imbhargav5** [comment]
Hi 👋 will look at it first thing tomorrow.

**Comment by vednig** [comment]
Any update, are you able to reproduce this?

**Comment by vednig** [comment]
That's great 🎉 , will you be using @supabase/ssr in it?
And is there any expected timeline for updates?

**Comment by vednig** [comment]
I have an app in production, facing this error and I can find a solution to this problem, other than rebuilding it from scratch.

**Comment by imbhargav5** [comment]
Yes . Already using supabase ssr. But it’s a bit inconsistent now. In about
1-2 weeks everything will be crisp.
